### ISSUE TITLE
What's New Module Error

### ISSUE THREAD

**Issue by abomadi** [YAFNET/YAFNET-DNN#12]
Error: YAF What's New is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Cannot insert the value NULL into column 'RankID', table 'dbo.yaf_User'; column does not allow nulls. INSERT fails. The statement has been terminated. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'RankID', table 'FY-DB-PRO.dbo.yaf_User'; column does not allow nulls. INSERT fails. The statement has been terminated. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction) at YAF.Classes.Data.LegacyDb.user_save(Object userID, Object boardID, Object userName, Object displayName, Object email, Object timeZone, Object languageFile, Object culture, Object themeFile, Object textEditor, Object useMobileTheme, Object approved, Object pmNotification, Object autoWatchTopics, Object dSTUser, Object hideUser, Object notificationType) at YAF.DotNetNuke.Components.Utils.UserImporter.CreateYafUser(UserInfo dnnUserInfo, MembershipUser dnnUser, Int32 boardID, Int32 portalID, YafBoardSettings boardSettings) at YAF.DotNetNuke.YafDnnWhatsNew.GetYafUserId() at YAF.DotNetNuke.YafDnnWhatsNew.BindData() --- End of inner exception stack trace ---

**Comment by w8tcha** [comment]
Looks like something is not correctly setup in your installation.

Login as Host and go to the YAF Module Settings and save them to make sure the board id is set correctly.

The other think that could go wrong is when there is no Rank in YAF which has the IsStart flag set to true
