### ISSUE TITLE
Redirection Loop

### ISSUE THREAD

**Issue by abomadi** [YAFNET/YAFNET-DNN#13]
After upgrading to the newers Beta1 version iam facing a redirection loop errors on Arabic Forum with main forum topics that have spaces between words, i tried to change the rewrite mode to translit or utf-8 and didnt work i even changed the dnn redirect to put + or %20 instead of spaces and still having the same issue, any idea ?

it gives error unfriendly URL

**Comment by abomadi** [comment]
temprorly solved by disable Redirect Mixed Case URLs in Site settings but it still an bug in Yaf

**Comment by w8tcha** [comment]
Can you post some example urls and/or topics that causes the problem?

**Comment by azarbara** [comment]
ingo the same problem is accord in the following url,
http://forum.ndsa.ir
when you click in forums that names has space 
get the redirect loop error
![capture](https://cloud.githubusercontent.com/assets/5406334/6244535/0a97be42-b76a-11e4-8218-a93d22bc1604.JPG)

![1221](https://cloud.githubusercontent.com/assets/5406334/6244534/0a94f068-b76a-11e4-8525-775f39bda4f0.JPG)
when repalce "%20" with "-" the problem resolved
ingo, this is critical error in live site, please figure out and help to solve it
thanks

**Comment by azarbara** [comment]
@abomadi could you please tell me where is the "Redirect Mixed Case URLs" and how disable it?
thanks

**Comment by w8tcha** [comment]
> this is critical error in live site, please figure out and help to solve it

working on it fixed version should be out tomorrow, if i have enough time

**Comment by azarbara** [comment]
ok thanks

**Comment by w8tcha** [comment]
updated build 5711 is online

https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.0-5711

**Comment by azarbara** [comment]
thanks so much
