### ISSUE TITLE
search issues

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#16]
Hey Ingo, 
there is an issue in quick search.
when i search for a Persian character in quick searchbox
![capture](https://cloud.githubusercontent.com/assets/5406334/6422177/e65b6636-beea-11e4-9c8c-dae35fe0fa53.JPG)
after clicking to search button in the next page the above entered character change to illegal characters and search no return any value
![capture](https://cloud.githubusercontent.com/assets/5406334/6422229/63015d94-beeb-11e4-9f9c-773e4392e013.JPG)

**Comment by w8tcha** [comment]
I can not reproduce the issue, but i uploaded build 5712 with a possible fix attempt.

https://github.com/YAFNET/YAFNET-DNN/releases/download/v2.2.0-5711/YAF_DNN_2.20.0-5712.zip

**Comment by azarbara** [comment]
thanks, i will test it and report the result!

**Comment by azarbara** [comment]
Ingo, thanks for your work, now everything is OK! and the problem was resolved.

**Comment by azarbara** [comment]
i replaced the above file DLLs to bin directory and now there is no problem
