### ISSUE TITLE
yaf whats new error

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#19]
Dear Ingo, 
I get the following error after add the whats new module to the page
<code>
خطا : جدیدترین ارسال‌های انجمن در حال حاضر در دسترس نیست DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at YAF.Core.ControlExtensions.HtmlEncode(Control currentControl, Object data) at YAF.DotNetNuke.YafDnnWhatsNew.ProcessItem(RepeaterItemEventArgs e) at YAF.DotNetNuke.YafDnnWhatsNew.LatestPostsItemDataBound(Object sender, RepeaterItemEventArgs e) at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem) at System.Web.UI.WebControls.Repeater.CreateControlHierarchy(Boolean useDataSource) at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e) at YAF.DotNetNuke.YafDnnWhatsNew.BindData() --- End of inner exception stack trace ---

</code>

yaf version: YAF_DNN_2.21.0-5714.zip

**Comment by w8tcha** [comment]
Fixed in BETA 2 Build 5715
https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.1-beta.2
