### ISSUE TITLE
localize time ago js

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#22]
Dear Ingo, Could you please help me to translate   
`<Resource tag="TIMEAGO_JS">      // defaults to english... no need for localization.</Resource>`
i want to localize the relative time in my forum.
Regards

**Comment by w8tcha** [comment]
you need to translate the resource string in the language file. Which language are you using?

**Comment by azarbara** [comment]
i'm using Persian, 
the resource in Persian.xml is 
`<Resource tag="TIMEAGO_JS"> // defaults to english... no need for localization.</Resource>
`
and there is not anything for translate

**Comment by w8tcha** [comment]
Replace the content with this...

``
jQuery.timeago.settings.strings = {
      prefixAgo: null,
      prefixFromNow: null,
      suffixAgo: "ago",
      suffixFromNow: "from now",
      seconds: "less than a minute",
      minute: "about a minute",
      minutes: "%d minutes",
      hour: "about an hour",
      hours: "about %d hours",
      day: "a day",
      days: "%d days",
      month: "about a month",
      months: "%d months",
      year: "about a year",
      years: "%d years",
      numbers: []
      };
``

then you can translate

**Comment by azarbara** [comment]
Ok thanks
