### ISSUE TITLE
some improvement for persian.xml

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#23]
Dear Ingo, 
i attached new xml file that has some improvement for persian language, please merge this file to project.
Regards

[persian.zip](https://github.com/YAFNET/YAFNET-DNN/files/194268/persian.zip)

**Comment by w8tcha** [comment]
Thanks i merged your file. but please next time make a pull request that would make it easier to merge.

**Comment by azarbara** [comment]
at this time i want to make a pull request and create a fork and open project with TFS in VS. but i can't handle it and nevermind:)
