### ISSUE TITLE
there is some confusing js replace in theme

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#24]
in the themes/Fancy/js/Fancy.js there is some confusing and mistake replace. 
` jQuery(".menuMyList .myProfile a").text("."), jQuery(".menuMyList .myPm a").text("%"), jQuery(".menuMyList .myBuddies a").text(","), jQuery(".menuMyList .myAlbums a").text("p"), jQuery(".menuMyList .myTopics a").text("9"), jQuery(".menuMyList .menuAccount a").text("E")
`
that cause mistake characters instead of texts 
![11](https://cloud.githubusercontent.com/assets/5406334/14123017/8ea85d8e-f613-11e5-82af-8c173aaaf5dd.JPG)
Please correct this replaces in project

**Comment by w8tcha** [comment]
Looks like for some reason the custom font is not loaded. Did you modify the theme.css for that theme?

**Comment by azarbara** [comment]
yes i have some standard modification in this file. like add Persian font-faces. and some changes for rtl direction.
now i remove above scripts and the problem resolved
