### ISSUE TITLE
broken profile picture

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#25]
@w8tcha , 
the profile pic has broken 
![image](https://cloud.githubusercontent.com/assets/5406334/15429107/5b19b502-1eb4-11e6-9e92-578e9bc2c71f.png)

and when **open image in new tab** the following message apeared

`Server Error in '/' Application.

Parameter is not valid.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: Parameter is not valid.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[ArgumentException: Parameter is not valid.]
   System.Drawing.Bitmap..ctor(Stream stream) +638721
   YAF.YafResourceHandler.GetResponseRemoteAvatar(HttpContext context) +616
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +508
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.81.0`

and this page url and parameters is: [here]http://miralavi.com/DesktopModules/YetAnotherForumDotNet/resource.ashx?url=http%3a%2f%2fmiralavi.com%2f%D9%BE%D8%B4%D8%AA%DB%8C%D8%A8%D8%A7%D9%86%DB%8C%2f%D8%A7%D9%86%D8%AC%D9%85%D9%86-%D9%87%D8%A7%DB%8C-%DA%AF%D9%81%D8%AA%DA%AF%D9%88%2fLinkClick.aspx%3ffileticket%3dwjQlF1wyUNM%253d&width=200&height=200)
there is some Persian character in URL. 
what is the problem?

**Comment by w8tcha** [comment]
i can not reproduce the error, but i have an idea how to fix that. Updated version soon.

**Comment by w8tcha** [comment]
I uploaded Build 5741, hopefully this fixes the issue

**Comment by azarbara** [comment]
:(
unfortunately the issue still remaining.

**Comment by w8tcha** [comment]
Looks like this is an url problem, 5742 is online

**Comment by azarbara** [comment]
Good Job :+1: 
the issue is resolved
