### ISSUE TITLE
hover card issue

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#26]
there is an issue in hover card, after hover in name the following message displayed. 
"SyntaxError: Unexpected token < in JSON at position 0"
![image](https://cloud.githubusercontent.com/assets/5406334/16577170/cdeb87dc-42a8-11e6-90fc-53e589d55e4c.png)
*****************************************
here is firebug's Console Params:
boardId	
1
forumUrl	
http://miralavi.com/پشتیبانی/انجمن-های-گفتگو
type	
json
userinfo	
2
*********************************************
the site language is Persian, 
DNN 7.4.2
YAF2.23.0-5742 (there was some problem in 2.2.2 version (2.22.0-5731)).

**Comment by w8tcha** [comment]
Its the same url problem. Fixed now in 5743

**Comment by azarbara** [comment]
thanks for new release.
