### ISSUE TITLE
YAF is not IPv6 compatible

### ISSUE THREAD

**Issue by marietteknap** [YAFNET/YAFNET-DNN#27]
![2016-08-14_10-02-10](https://cloud.githubusercontent.com/assets/5551768/17647961/4886dd8a-6206-11e6-9afc-041e3b3f0c10.png)

**Comment by eakratsada** [comment]
h
[Presales eGuide 11108.pdf](https://github.com/YAFNET/YAFNET-DNN/files/542714/Presales.eGuide.11108.pdf)

[Order eGuide 11108.pdf](https://github.com/YAFNET/YAFNET-DNN/files/542715/Order.eGuide.11108.pdf)
[Uploading Presales eGuide 11108.pdf…]()
[Sales eGuide 11108.pdf](https://github.com/YAFNET/YAFNET-DNN/files/542716/Sales.eGuide.11108.pdf)
[Support eGuide 11108.pdf](https://github.com/YAFNET/YAFNET-DNN/files/542717/Support.eGuide.11108.pdf)

**Comment by w8tcha** [comment]
Fixed with https://github.com/YAFNET/YAFNET/commit/be9f1868480fb6e3cb4c47622c284d16f2a8b0af

will be included in YAF.NET v2.2.4
