### ISSUE TITLE
How to clean up the URL's?

### ISSUE THREAD

**Issue by hismightiness** [YAFNET/YAFNET-DNN#30]
Does anyone have any instructions on how to make the URL's much more SEO and human friendly?

http://example.com/Forums/g/posts/m/3/New-site-going-live-but-need-advice

Ideally, I'd like to get rid of **/g/posts/m/3** since it doesn't at all do anything for the forum visitors or search engines.

**Comment by toshno** [comment]
I have same issues. Looking at this post maybe it will not be fixed

**Comment by w8tcha** [comment]
No this won't change at the moment
