### ISSUE TITLE
DNN 9.1.1 - Fresh YAF installation (YAF_DNN_2.24.3-5804) - Runtime Error

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#32]
System reports that the installation completed successfully.  After page refresh, get a runtime error:

Could not load file or assembly 'DotNetNuke, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.IO.FileLoadException: Could not load file or assembly 'DotNetNuke, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Source Error: 
 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 
[FileLoadException: Could not load file or assembly 'DotNetNuke, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)]
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) +0
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) +95
   System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) +53
   System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +44
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +61
   DotNetNuke.ComponentModel.ProviderInstaller.InstallProvider(IContainer container, Provider provider) +94
   DotNetNuke.ComponentModel.ProviderInstaller.InstallComponents(IContainer container) +260
   DotNetNuke.ComponentModel.ComponentFactory.InstallComponents(IComponentInstaller[] installers) +70
   DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication.Application_Start(Object sender, EventArgs eventArgs) +2129

[HttpException (0x80004005): Could not load file or assembly 'DotNetNuke, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +529
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +169
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +169
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +396
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +333

[HttpException (0x80004005): Could not load file or assembly 'DotNetNuke, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +525
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +124
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +700

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2106.0

**Comment by w8tcha** [comment]
Which dnn version are you using?

Did you use an official installation of dnn?

**Comment by JaySMa** [comment]
This is DNN version 9.1.1; upgraded from 7.4.1, to 8.0.4, to 9.1.1.

Yes, official DNN version 9.1.1 upgrade.  Thank you..

**Comment by w8tcha** [comment]
Okay found the problem nuget adds a specific version.

Issue is fixed in v2.2.4.3-5805 i updated the downloads
