### ISSUE TITLE
DNN 9.1.1 - YAF-2.24-3-5807

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#33]
Top menu bar area (where it shows logged in as, my profile, etc.), the "Forum" link enters the page name twice in the URL.

E.g.  http://testwebsite/YAF-ForumYAF-Forum

So when you click on this link, it causes a 404 error.

This also occurs during the installation of the extension.   After getting to the "CREATE, SELECT OR IMPORT A BOARD..." and "OTHER SETTINGS..." information area, and click on the UPDATE button, you're re-directed to http://testwebsite/YAF-ForumYAF-Forum and thus get a 404 error.

If there are any other areas, I'll update this.  Thank you..

**Comment by w8tcha** [comment]
i released build 5808
https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.3-5808

i tried a more simpler approach to get the main url.

**Comment by JaySMa** [comment]
Hello..
This appears to have resolved the URL issue.  Thank you..
