### ISSUE TITLE
yaf_Message - Message Column configured for ntext (being depreciated)

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#34]
As per Microsoft, ntext is being depreciated, will be replaced in upcoming SQL versions and replaced with nvarchar(max).

https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql

I found that when within SQL management studio making changes to the table (nulling Edited date/time and EditReason), it was stating that my message was going to be truncated.

"No row was updated. The data in row 24 was not committed. Error Source: .Net SqlClient Data Provider. Error Message: String or binary data would be truncated. The statement has been terminated. Correct the errors and retry or press ESC to cancel the change(s)."

I changed changed this column to nvarchar(max) and when saved, it states the following tables need to be save to your database; yaf_User, yaf_Message, yaf_Topic, yaf_Forum and yaf_MessageHistory.

I went ahead and made the change, but didn't notice any issues and didn't have any further issues.

**Comment by w8tcha** [comment]
really all you need to is alter the colum

`ALTER TABLE dbo.yaf_Message ALTER COLUMN [Message] NVARCHAR(MAX)`

in the next version of YAF 2.3.0 all columns are been changed from ntext to nvarchar(max)

**Comment by JaySMa** [comment]
Thank you.
