### ISSUE TITLE
DNN Super Users - Not added to YAF "Administrator" Role

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#36]
Portal Administrators are automatically added to the "Administrator" security role, but any SuperUser account is not.

Seems like they have the ability to change the settings and add themselves to the Administrators role though.  It just isn't automatically added during the installation of the YAF module.  Nothing major.

Thank you..

**Comment by w8tcha** [comment]
Are the Superuser are part of the Admin role inside dnn? By default mirrors the roles from dnn. But i can add that automatically if thats needed.

**Comment by JaySMa** [comment]
The Superuser or Host user is an account which has complete control over everything concerning the DNN installation.  Using this account, you have special accesses to the servers host settings and you can use it's credentials to log into any and every portal.  In essence, it's the ultimate Administrator. ha-ha..

**Comment by w8tcha** [comment]
I use dnn since version 3 i know what the host user is, and really in yaf the host user is similar. But as i write before the roles are automatically mirrored. if the user is part of the admin role it would automatically assigned to the admin role in yaf

**Comment by w8tcha** [comment]
su are now correctly imported in build 5811
