### ISSUE TITLE
DNN - Absolute URL's

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#37]
Hello..
DNN allows for website aliases, thus allowing you to have a website respond to multiple url requests (with proper IIS bindings, etc).

I noticed the Avatar column for a user, is hard coded with the URL of the domain which the account was created, or copied over from when YAF-DNN was installed.  For example, I'm working on a development box, so the Avatar of the user is hard-coded with the development's URL.  When I move it to our live server, I'll need to update these locations with an update script to the live domain URL; not a problem, but others may not know how to fix.

If you could update the code which displays the Avatar and change it to a relative URL, this would fix the hard-coding of the Avatars.   For example, "/Portals/0/Users/002/02/2/admin_photo.png?ver=2014-08-27-070025-283" would be fed to the code and the proper URL would be generated to display the avatar.

For example on a DNN skin we can enter, "<img src="<% =SkinPath %>/assets/img/seal.png" alt="Seal" />" and no matter what the URL is (whether development, live, etc.), the image will display properly and it's not hard-coded into the skin file.

Thank you for your time and attention..

**Comment by w8tcha** [comment]
Yes i understand the problem, with the current logic the url itself need to be absolute but only when the avatar is displayed. With the next update the urls will be saved as relative urls

> When I move it to our live server, I'll need to update these locations with an update script to the live domain URL; not a problem, but others may not know how to fix.

You only need to press the "Syncronize Users" Button and all avatars will be updated
