### ISSUE TITLE
vv2.2.4.5-5810 - Admin -> Maintenance -> Attachments text for link not shown

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#39]
After upgrade, the Attachments link text isn't shown.  Clicking on the icon takes you to the Admin -> Active Users page.

Looking at the code, it shows the SPAN and being empty.
`<span style="margin-left:3px;"></span>`

Thanks..

**Comment by w8tcha** [comment]
Ignore this page it will be removed with the next release

**Comment by w8tcha** [comment]
i re-uploaded the latest version, that page is now completely removed
