### ISSUE TITLE
YAF-DNN v2.2.4.5-5811 - User Avatars

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#42]
Hello..
The user avatar URL's are configured as such and won't display properly; /Portals/0/Users/003/03/3/Avatar.jpg

If you click on the update button, the system doesn't enter the domain URL and just enters a "http://" at the beginning; http:///Portals/0/Users/003/03/3/Avatar.jpg

Manually putting in the domain allows the avatar to show up properly.

Thank you for your time and attention..

**Comment by w8tcha** [comment]
>> The user avatar URL's are configured as such and won't display properly; /Portals/0/Users/003/03/3/Avatar.jpg

Actually that is correct the avtars are stored as relative urls to handle portals with multiple domains correctly. Only the display part was not working correctly. Fixed in latest build 5812
