### ISSUE TITLE
YAF-DNN v2.2.4.5-5811 - "Host Admin" access needed for Administrators

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#43]
Hello..
This isn't major for us since we're only running one board on the forum, but have found that even if a user is configured as an Administrator (both DNN and YAF), when trying to access the Administration pages, it reports that you need Host Admin access to view that page.

Checking Host Admin for the user allows them to access the admin area.

Thank you for your time and attention..

> Host Admin permissions reqired!
> To access the area your board's Host Admin should set some extra permissions for you.

Also, after updating realized "reqired" is mis-spelled above.

**Comment by w8tcha** [comment]
That is correct, you need to go to Host > Host Administration > Admin Page Access > And set for each Administrator which page you want to give them access to.

**Comment by w8tcha** [comment]
the spelling error will be fixed with the next upgrade
