### ISSUE TITLE
YAF-DNN - Feature Request Remote URL for Forum

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#44]
Hello..
We are using this to link to a file locally stored on the server.

Maybe adding a browse button to this  (or add another line to link to local file) so people can browse the portal folder structure and select the file to be used.

But too, this adds another issue in that this would need to be stored as a relative URL so moving to another server (development to live) won't affect the forum.

Thank you for your time and attention.

**Comment by JaySMa** [comment]
There's a setting within the forum configuration which allows you to select an Remote URL for the forum.  When someone selects the forum, they're redirected to this remote URL.

In this case, the old forum was linked to a PDF stored on the server.  This is why I brought this up.

Thanks again..

**Comment by w8tcha** [comment]
In YAF 2.24.16 you can now use relative urls!
