### ISSUE TITLE
Albums Not Displaying Images in Lightbox / Slideshow

### ISSUE THREAD

**Issue by birksy89** [YAFNET/YAFNET-DNN#48]
Hello,

I'm having an issue with the Albums which are connected to a user profile page.

I've managed to upload some images, but when trying to load the lightbox, only the selected image loads in the pop-up:
![prev](https://user-images.githubusercontent.com/4971630/43194383-208ccfa0-8ffa-11e8-82b2-3d0d1d31b145.PNG)

When you try to navigate to the "next" / "prev" images - A white area appears:
![white](https://user-images.githubusercontent.com/4971630/43194255-dc6adc2c-8ff9-11e8-897a-7b86568e8271.PNG)

Is it possible to access this feature via the code - I've cloned the code to my PC and done a search through the files - But can't find a reference to "album" anywhere.

Please let me know where I'm going wrong.

Thanks in advance
-Andrew

**Comment by birksy89** [comment]
Can you point me towards the code that is used to generate the albums.

I was going to try and see if Fancybox could replace it - But doing a quick search through all the files, I couldn't find the code.

Just let me know if I can help

Thanks

**Comment by w8tcha** [comment]
that jquery ceebox script that generated the lightbox is minified in the Scripts/jquery.ForumExtensions.min.js file and if you download the source then the file is in Scripts/jquery.ceebox.js

**Comment by birksy89** [comment]
I've cloned the source from Github previously - And can't find a folder called Scripts.

I couldn't get the solution to build either.

Doing a search through the files which are there I only found this reference:
 <DefaultExclude Include="$(MSBuildProjectDirectory)\..\yafsrc\YetAnotherForum.NET\Scripts\jquery.ceebox.js" />

And that folder location doesn't exist in the file structure I've got.

Sorry to be a pain - Please let me know where I'm going wrong

**Comment by w8tcha** [comment]
Sorry but for compiling the module you need to clone the YAF-DNN repository and the main YAFNET Repository (Stable branch not master branch).

I updated the wiki page...
https://github.com/YAFNET/YAFNET-DNN/wiki/Build-Module-Package-from-Source

**Comment by w8tcha** [comment]
Okay found the issue! Similar problem as with the tabs. Because of the removed selector api in jquery 3.

New build is online

https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.13-5820
