### ISSUE TITLE
What's new generating incorrect url

### ISSUE THREAD

**Issue by toshno** [YAFNET/YAFNET-DNN#49]
I am using DNN 9.3 . Added the What's New module but it is generating wrong url. Example correct url :  https://www.fowara.com/forums/g/posts/t/2/installing-login-as-customer but the What's new linking at:  https://www.fowara.com/tabid/66/g/posts/m/2/Installing-Login-as-Customer.aspx#post2

Is there any way to fix this?

**Comment by w8tcha** [comment]
The tabid URL parameter is needed to work.

**Comment by toshno** [comment]
it's not abut removing tabid. It's about it's generating link that returns 404

**Comment by w8tcha** [comment]
I cannot reproduce it, but i changed the urls like you suggested.

https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.17-5825

Can you confirm that it works with YAF 2.24.17?
