### ISSUE TITLE
Runtime Error (YAF_DNN_2.30.0-35903/DNN9.4.4)

### ISSUE THREAD

**Issue by rthoeni** [YAFNET/YAFNET-DNN#50]
Steps to repro: (WIN 2016, SQL 2014, ASP.net 4.8)

Step 1:
New Install DNN 9.4.4
Install Bootstrap 4 Theme
Install YAF YAF_DNN_2.24.2-05828
Upgrade YAF_DNN_2.30.0-35903
_> Runtime Error_

Step 2:
New Install DNN 9.4.4
Install Bootstrap 4 Theme
Install YAF YAF_DNN_2.30.0-35903
_> Runtime Error_

--------Runtime Error-----
Event code: 3005 
Event message: Es ist eine unbehandelte Ausnahme aufgetreten. 
Event time: 27.12.2019 13:08:07 
Event time (UTC): 27.12.2019 12:08:07 
Event ID: c0d0d9953d2843d3af681b654768be6f 
Event sequence: 2 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/5/ROOT-11-132219220850488518 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: D:\WEB\xy\ 
    Machine name: VPSxy  
 
Process information: 
    Process ID: 10116 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\xy  
 
Exception information: 
    Exception type: TypeInitializationException 
    Exception message: Der Typeninitialisierer für "YAF.Core.GlobalContainer" hat eine Ausnahme verursacht.
   bei YAF.Core.YafTaskModule.Init(HttpApplication httpApplication)
   bei System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   bei System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   bei System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   bei System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)

Die Datei oder Assembly "System.Web.Http.WebHost, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes()
   bei YAF.Core.Extensions.AssemblyExtensions.<>c__DisplayClass0_0`1.<FindClassesWithAttribute>b__0(Assembly a)
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei YAF.Types.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 list, Action`1 action)
   bei YAF.Core.Extensions.AssemblyExtensions.FindClassesWithAttribute[T](IEnumerable`1 assemblies)
   bei YAF.Core.Modules.DynamicServicesModule.RegisterDynamicServices(Assembly[] assemblies)
   bei YAF.Core.Modules.DynamicServicesModule.Load(ContainerBuilder containerBuilder)
   bei YAF.Core.BaseModule.Configure(IComponentRegistry componentRegistry)
   bei Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   bei YAF.Core.Extensions.IHaveComponentRegistryExtensions.UpdateRegistry(IHaveComponentRegistry haveComponentRegistry, ContainerBuilder containerBuilder)
   bei YAF.Core.Modules.BootstrapModule.Load(ContainerBuilder builder)
   bei YAF.Core.BaseModule.Configure(IComponentRegistry componentRegistry)
   bei Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   bei Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   bei YAF.Core.GlobalContainer..cctor()

 
 
Request information: 
    Request URL: http://www.xyz.xyz/DesktopModules/YetAnotherForumDotNet/install/ 
    Request path: /DesktopModules/YetAnotherForumDotNet/install/ 
    User host address: XXXX.XXX.XXX.XXX 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\xy 
 
Thread information: 
    Thread ID: 47 
    Thread account name: IIS APPPOOL\xy  
    Is impersonating: False 
    Stack trace:    bei YAF.Core.YafTaskModule.Init(HttpApplication httpApplication)
   bei System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   bei System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   bei System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   bei System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
 
 
Custom event details:

**Comment by w8tcha** [comment]
Are you using the default web.config from the dnn installation?

It should contain...

` <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31BF3856AD364E35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.7.0" newVersion="5.2.3.0" />
      </dependentAssembly>`

**Comment by rthoeni** [comment]
Ingo, i have this here in all my DNN (include the new Install):

<dependentAssembly><assemblyIdentity name="System.Web.Http" publicKeyToken="31BF3856AD364E35" /> <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" /> </dependentAssembly>

**Comment by w8tcha** [comment]
sorry my bad. please change it to ...

`<dependentAssembly><assemblyIdentity name="System.Web.Http" publicKeyToken="31BF3856AD364E35" /> <bindingRedirect oldVersion="0.0.0.0-5.2.7.0" newVersion="5.2.3.0" /> </dependentAssembly>`

and also

`<dependentAssembly>
        <assemblyIdentity name="System.Web.Http.WebHost" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.7.0" newVersion="5.2.3.0" />
      </dependentAssembly>`

issue will be fixed with the next update.
