### ISSUE TITLE
Could not load type 'YAF.YafResourceHandler' from assembly 'YAF' (YAF_DNN_2.30.0-35903/DNN9.4.4)

### ISSUE THREAD

**Issue by rthoeni** [YAFNET/YAFNET-DNN#51]
AbsoluteURL:/DesktopModules/YetAnotherForumDotNet/resource.ashx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:63775bc8-a792-4403-8fec-6f06a201b52e

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:8Dt264aCCSGKjE///vjxBZ3xfZY=

Message:Unhandled Error:

StackTrace:

InnerMessage:Could not load type 'YAF.YafResourceHandler' from assembly 'YAF'.

InnerStackTrace:

   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at System.Web.Configuration.HandlerFactoryCache.GetTypeWithAssert(String type)
   at System.Web.Configuration.HandlerFactoryCache.GetHandlerType(String type)
   at System.Web.Configuration.HandlerFactoryCache..ctor(String type)
   at System.Web.HttpApplication.GetFactory(String type)
   at System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: vpsxy

**Comment by rthoeni** [comment]
Ingo this is the Message after Upgrade (Post https://github.com/YAFNET/YAFNET-DNN/issues/50)

**Comment by w8tcha** [comment]
change the line in the web.config from...

`<add name="YafHandler" preCondition="integratedMode" verb="GET" path="Resource.ashx" type="YAF.YafResourceHandler, YAF" />`

to

`<add name="YafHandler" preCondition="integratedMode" verb="GET" path="Resource.ashx" type="YAF.Core.Handlers.YafResourceHandler, YAF.Core" />`

**Comment by rthoeni** [comment]
Thanks Ingo
Now this Error here:

AbsoluteURL:/DesktopModules/YetAnotherForumDotNet/resource.ashx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:977311ea-56ef-4316-b7d7-66f0482ff6e3
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:+OtXim9UgRZoHiCzzda+BHnNHJE=
Message:Unhandled Error:
StackTrace:
InnerMessage:Parameter is not valid.
InnerStackTrace:
   at System.Drawing.Bitmap..ctor(Stream stream)
   at YAF.Core.Services.YafResources.GetResponseRemoteAvatar(HttpContext context)
   at YAF.Core.Handlers.YafResourceHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

**Comment by rthoeni** [comment]
That works for me :)
Go in the Profile Settings, delete the Image (User Image), save

**Comment by w8tcha** [comment]
Does this error come when you are logged in? Does the user has an dnn avatar set?

**Comment by rthoeni** [comment]
This error occurs when a profile picture is stored in DNN and logged in.
>  If I delete the profile picture, this error has already been fixed.

Another error comes when clicking on Privacy Policy goes, I accept the rules, register and the YAF Captcha image is not displayed for non-logged in users You can see an icon but no code (resource.ashx)
> can no longer create the error because now the lower one is new, sorry

---------------Error-----------------
12/28/2019 08:46:22
Page Load Exception
 
XY 
AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:2a9048bc-7ff4-45ab-acae-125e86130f63
AssemblyVersion:9.4.4
PortalId:0
UserId:-1
TabId:46
RawUrl:/g/register
Referrer:/g/rules
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15
ExceptionHash:uB3MweFfWQwQ234MR4Au8HM0kOI=
Message:Zeichenfolgen- oder Binärdaten würden abgeschnitten. Die Anweisung wurde beendet.
StackTrace:
InnerMessage:Zeichenfolgen- oder Binärdaten würden abgeschnitten. Die Anweisung wurde beendet.
InnerStackTrace:
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   bei System.Data.SqlClient.SqlDataReader.get_MetaData()
   bei System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteScalar()
   bei ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ExecLongScalar(IDbCommand dbCmd, String sql)
   bei ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Action`1 commandFilter, Boolean selectIdentity)
   bei ServiceStack.OrmLite.OrmLiteWriteApi.<>c__DisplayClass5_0`1.<Insert>b__0(IDbCommand dbCmd)
   bei ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
   bei YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction)
   bei YAF.Core.Extensions.IRepositoryExtensions.Insert[T](IRepository`1 repository, T entity, IDbTransaction transaction)
   bei YAF.Core.Services.Logger.YafDbLogger.Log(String message, EventLogTypes eventType, String username, String source, Exception exception)
   bei YAF.Types.Interfaces.LoggerExtensions.Log(ILogger logger, String username, Object source, String description, EventLogTypes eventType)
   bei YAF.Pages.register.Page_Load(Object sender, EventArgs e)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei System.Web.UI.Control.OnLoad(EventArgs e)
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

**Comment by w8tcha** [comment]
> This error occurs when a profile picture is stored in DNN and logged in

I cannot reproduce this. But can you post the error from the yaf event log ? Admin >  Maintenance > Event log

**Comment by rthoeni** [comment]
Ingo, i have now also made a test installation to be able to narrow down the errors.
DNN 9.4.4, YAF 2.30

Web 1)
Show "Rules" Disabled before registration. > Error 
Errors in DNN admin logs recorded (Errors described above)
Admin > Maintenance > Event log (No Entries found)

Web2)
Show "Rules" active before registration. > Error (No CAPTCHA visible, only Image ?)
Generate new image, no changes (No CAPTCHA visible, only Image ?)
Admin > Maintenance > Event log (No Entries found)
![DNN_YAF_Error_YafCaptcha](https://user-images.githubusercontent.com/12658708/71548342-34caac00-29ad-11ea-825f-89c579c2d7a4.PNG)

is there a way to make the privacy policy invisible in this line?
**Privacy Policy** | Powered by YAF.NET | YAF.NET © 2003-2019, Yet Another Forum.NET

**Comment by w8tcha** [comment]
the link will be hidden in the next update!
