### ISSUE TITLE
Page Load Exception (YAF_DNN_2.30.0-35903/DNN9.4.4)

### ISSUE THREAD

**Issue by rthoeni** [YAFNET/YAFNET-DNN#52]
Steps to repro: (Sorry for my English)
1) Go to Verwaltung> Foren> Forum Hinzufügen / Bearbeiten
2) In the Tab Zugangsmasken, can not change the Access (Example Registered Users or others) 
3) click button save 
(>Example: Test Forum: Admin/Member have only XXXX Access on a new Install, can not change and save)

--------------Error-------------
Es ist ein kritischer Fehler aufgetreten, weitere Details finden Sie im Ereignisprotokoll dieser Website.

Check
12/27/2019 21:20:57
Page Load Exception
hans.meier 
XY 
AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:71938e62-17a1-4458-9077-bb02317c7e4a
AssemblyVersion:9.4.4
PortalId:0
UserId:1
TabId:46
RawUrl:/kretipleti/news/g/admin_editforum/fa/2
Referrer:https://www.xy.xyz/kretipleti/news/g/admin_editforum/fa/2
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
ExceptionHash:LFTAEGJmWtHzZj+PyVRrntdgm+4=
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
StackTrace:
InnerMessage:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
InnerStackTrace:
   bei YAF.Pages.Admin.editforum.<>c__DisplayClass59_0.<SaveClick>b__0(RepeaterItem item)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei YAF.Pages.Admin.editforum.SaveClick(Object sender, EventArgs e)
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: vps74

**Comment by w8tcha** [comment]
It's a known issue 

https://github.com/YAFNET/YAFNET/issues/503

And will be fixed in 2.30.04

**Comment by rthoeni** [comment]
Thanks Ingo, I close here :)
