### ISSUE TITLE
Forums are not shown (DNN 9.4.4/YAF.NET v2.30.04)

### ISSUE THREAD

**Issue by rthoeni** [YAFNET/YAFNET-DNN#53]
Sorry Ingo, I'm coming again
--> When a new forum is created, it is not displayed
It doesn't matter whether you are logged in or not

Steps to repro:
1) Create a new forum in the category
![Foren_hinzufuegen](https://user-images.githubusercontent.com/12658708/71576617-78c6c980-2af1-11ea-890a-bced4af02dab.PNG)

2) Forum settings
![Foren_einstellungen](https://user-images.githubusercontent.com/12658708/71576660-a01d9680-2af1-11ea-8218-a8575a088c65.PNG)

3) Presentation on the page
![Foren_ansicht](https://user-images.githubusercontent.com/12658708/71576740-ea9f1300-2af1-11ea-9ec0-ae4b44f645ae.PNG)

It is not possible to add anything.. I don't bring the forums visible :)

---------- an additional question but not important -------------
small remark on the side
can the button upwards be deactivated?
![nach_oben](https://user-images.githubusercontent.com/12658708/71576851-49648c80-2af2-11ea-843e-508c1299fd6d.PNG)

The page numbering overlaps with the text
![Foren_Nummern](https://user-images.githubusercontent.com/12658708/71576923-7dd84880-2af2-11ea-844b-3c120aef6aa2.PNG)

**Comment by w8tcha** [comment]
New version 2.30.05 is online! Issue with the new forums is fixed

> can the button upwards be deactivated?

New host setting under display > Show Scroll Back to Top button
