### ISSUE TITLE
YAF-DNN-2.30.07-5907, failed with 0 errors

### ISSUE THREAD

**Issue by rthoeni** [YAFNET/YAFNET-DNN#54]
**Describe the bug**

**To Reproduce**
1. Go to 'download YAF DNN'
2. Click on 'DNN Extension and upload, after ca. 86% upload of zip file failed with 0 errors'
3. Scroll down to 'Show error log, shows no errors'
4. See error trying again doesn't work

**Expected behavior**

**Screenshots**

**System (pletemase complete the following information):**
 - YAF Version: [e.g. YAF v2.24.20/2.30.4]
 - .NET Version [e.g. 4.8]
 - SQL Server [e.g. SQL Server 2014]
 
**Affected browser**

* [ ] Chrome
* [X] Firefox
* [X ] Safari
* [X ] Edge

**Additional context**
The last version 2.30.4 could be installed without any problems.

**Comment by w8tcha** [comment]
For some reason the zip file can't be read anymore. I switched the zip engine, and updated the downloads. Does it work now?

**Comment by rthoeni** [comment]
Thanks Ingo, very quickly :)
Your forum has now been upgraded to the latest version.
