### ISSUE TITLE
Checking, unchecking multiquote causes css classes to disappear on element

### ISSUE THREAD

**Issue by thx1200** [YAFNET/YAFNET-DNN#55]
**Describe the bug**
Multiquote button css class issue.  When checking, then unchecking checkbox, most of the classes disappear, which causes the bootstrap styling to also disappear.

**To Reproduce**
1. Go to a post
2. Click on multiquote
3. Uncheck multiquote
4. Examine classes on span.

**Expected behavior**
Styling persists

**Screenshots**
BEFORE CHECKING, span classes: MultiQuoteButton custom-control custom-checkbox btn btn-link
AFTER CHECKING, span classes: MultiQuoteButton custom-control custom-checkbox btn btn-link Checked
AFTER UNCHECKING, span classes: MultiQuoteButton

**System (please complete the following information):**
 - YAF Version: 2.3.1.04
 
**Affected browser**
At least Chrome

**Additional context**
N/A

**Comment by w8tcha** [comment]
Thanks, Issue will be fixed in 2.31.05
