### ISSUE TITLE
Cannot install YAF 3.1.5 on latest DNN 9.10.2

### ISSUE THREAD

**Issue by erw13n** [YAFNET/YAFNET-DNN#72]
**Describe the bug**
It broke entire site after install YAF forum.
- web.config been update and `<mimeMap fileExtension=".json" mimeType="application/json" />` been added, remove this will solve first issue.
- After refresh the page, PersonaBar is no longer work, it looking for System.Web.Http 5.2.8, while DNN 9.10.2 still using 5.2.6

**To Reproduce**
1. Install YAF on new DNN 9.10.2
2. Module Installation run smooth.
3. Refresh the website, and it goes blank. Check browse console, as it throw many error
4. Update web.config (remove json mime)
5. Refresh the site, and persona bar no longer work

**System (please complete the following information):**
 - YAF Version: 3.1.5
 - DNN 9.10.2

**Comment by erw13n** [comment]
I do a fresh DNN with nvQuicksite.
After install the module, persona bar showing this message:
![image](https://user-images.githubusercontent.com/792847/171400872-71d7a848-45b6-4a30-a723-7d48e2c73fba.png)

And when refresh the site, it load without css, and show this error:
![image](https://user-images.githubusercontent.com/792847/171401312-99e1dfb2-fffe-43a1-85de-c9bc763106ac.png)

Opening one of css, the error pointing about Json Mime:
![image](https://user-images.githubusercontent.com/792847/171401407-95d75532-ddbc-48d7-b9fc-383557687a32.png)

**Comment by w8tcha** [comment]
Thanks, issue is fixed now with latest release
