### ISSUE TITLE
Friend and Profile Sync

### ISSUE THREAD

**Issue by abomadi** [YAFNET/YAFNET-DNN#9]
Is there anyway to integrate friends and profile to be the same as DNN friend list and profile information ? if not it would be an amazing enhancement to this module

**Comment by RawbertVegan** [comment]
That would be pretty cool!

**Comment by abomadi** [comment]
Any idea about this error ?

Error while Syncing dnn userprofile with Yaf System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Common.Globals.NavigateURL() at YAF.DotNetNuke.DotNetNukeUrlBuilder.BuildUrl(Object boardSettings, String url) at YAF.Utils.YafBuildLink.GetBasePath(YafBoardSettings boardSettings) at YAF.DotNetNuke.Components.Utils.ProfileSyncronizer.SaveDnnAvatar(String fileId, Int32 yafUserId, Guid portalGUID, YafBoardSettings boardSettings) at YAF.DotNetNuke.Components.Utils.ProfileSyncronizer.SyncYafProfile(Int32 yafUserId, YafUserProfile yafUserProfile, IUserData yafUserData, UserInfo dnnUserInfo, Guid portalGUID, YafBoardSettings boardSettings) at YAF.DotNetNuke.Components.Utils.ProfileSyncronizer.UpdateUserProfile(Int32 yafUserId, YafUserProfile yafUserProfile, IUserData yafCurrentUserData, UserInfo dnnUserInfo, MembershipUser membershipUser, Int32 portalID, Guid portalGuid, YafBoardSettings boardSettings, Boolean ignoreLastUpdated)

**Comment by abomadi** [comment]
Also i have looked into Yaf database table which i think it takes much space by saving the eventlog on the database and users , profiles tables takes much space i think you have to consider reengineer this part.

Appreciated

**Comment by w8tcha** [comment]
> Any idea about this error ?
Which YAF version?

**Comment by abomadi** [comment]
Your YAF.NET Version: 2.2.0 BETA 20150110 (Date: 1/10/2015).

**Comment by w8tcha** [comment]
You might should consider upgrading to 2.2.1 BETA 2 released today, that issue has already been fixed.

**Comment by w8tcha** [comment]
> Also i have looked into Yaf database table which i think it takes much space by saving the eventlog on the database and users , profiles tables takes much space i think you have to consider reengineer this part.

The same is true for the DNN event log, but you can always clear out those event log tables and/or limit the amount of entries.

**Comment by abomadi** [comment]
i will perform the upgrade and let you know. Thanks
